# Generated by Django 2.2.7 on 2019-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='GKHandling',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
